import React from 'react';
import type { Subject, Chapter } from '../types';
import MarkdownRenderer from './MarkdownRenderer';

interface TestPaperProps {
    subject: Subject;
    chapter: Chapter;
}

// Using forwardRef to allow react-to-print to access the DOM node
const TestPaper = React.forwardRef<HTMLDivElement, TestPaperProps>(({ subject, chapter }, ref) => {
    const mcqs = (chapter.questions || []).filter(q => q.type === 'MCQ');
    const subjective = (chapter.questions || []).filter(q => q.type !== 'MCQ');

    return (
        <div ref={ref} className="p-12 max-w-4xl mx-auto bg-white print:p-8">
            {/* Header */}
            <div className="border-b-2 border-slate-900 pb-6 mb-8 text-center">
                <h1 className="text-3xl font-bold text-slate-900 mb-2">PrepMate Class 9</h1>
                <h2 className="text-xl font-semibold text-slate-700">{subject.name} - {chapter.title}</h2>
                <div className="flex justify-between mt-4 text-sm font-medium text-slate-600">
                    <span>Date: _______________</span>
                    <span>Time: 1 Hour</span>
                    <span>Max Marks: {mcqs.length + (subjective.length * 3)}</span>
                </div>
            </div>

            {/* Instructions */}
            <div className="mb-8 p-4 bg-slate-50 border border-slate-200 rounded-lg text-sm text-slate-700">
                <p className="font-bold mb-1">Instructions:</p>
                <ul className="list-disc list-inside space-y-1">
                    <li>All questions are compulsory.</li>
                    <li>MCQs carry 1 mark each.</li>
                    <li>Subjective questions carry 3 marks each.</li>
                </ul>
            </div>

            {/* MCQs */}
            {mcqs.length > 0 && (
                <div className="mb-8">
                    <h3 className="text-lg font-bold text-slate-900 mb-4 border-b border-slate-200 pb-2">
                        Section A: Multiple Choice Questions (1 Mark each)
                    </h3>
                    <div className="space-y-6">
                        {mcqs.map((q, idx) => (
                            <div key={idx} className="break-inside-avoid">
                                <div className="flex gap-2 mb-2">
                                    <span className="font-bold">{idx + 1}.</span>
                                    <div className="flex-1">
                                        <MarkdownRenderer>{q.text}</MarkdownRenderer>
                                    </div>
                                </div>
                                <div className="grid grid-cols-2 gap-4 ml-6">
                                    {q.options.map((opt, oIdx) => (
                                        <div key={oIdx} className="flex items-start gap-2">
                                            <span className="font-medium text-slate-500">
                                                {String.fromCharCode(65 + oIdx)}.
                                            </span>
                                            <MarkdownRenderer>{opt}</MarkdownRenderer>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Subjective */}
            {subjective.length > 0 && (
                <div>
                    <h3 className="text-lg font-bold text-slate-900 mb-4 border-b border-slate-200 pb-2">
                        Section B: Subjective Questions (3 Marks each)
                    </h3>
                    <div className="space-y-8">
                        {subjective.map((q, idx) => (
                            <div key={idx} className="break-inside-avoid">
                                <div className="flex gap-2">
                                    <span className="font-bold">{mcqs.length + idx + 1}.</span>
                                    <div className="flex-1">
                                        <MarkdownRenderer>{q.text}</MarkdownRenderer>
                                    </div>
                                </div>
                                <div className="mt-8 border-b border-slate-200 border-dashed"></div>
                                <div className="mt-8 border-b border-slate-200 border-dashed"></div>
                                <div className="mt-8 border-b border-slate-200 border-dashed"></div>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            <div className="mt-12 text-center text-xs text-slate-400">
                Generated by PrepMate - Practice & Excel
            </div>
        </div>
    );
});

TestPaper.displayName = 'TestPaper';

export default TestPaper;
